# Generated by Django 3.0.9 on 2020-08-29 02:27

import autoslug.fields
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject of Note')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='subject', unique=True, verbose_name='Note Address')),
                ('summary', models.TextField(blank=True, verbose_name='Summary')),
                ('details', models.TextField(blank=True, verbose_name='Details')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
