# Generated by Django 3.0.9 on 2020-08-29 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20200829_0228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={},
        ),
        migrations.RemoveField(
            model_name='note',
            name='created',
        ),
        migrations.RemoveField(
            model_name='note',
            name='modified',
        ),
    ]
