# Generated by Django 3.0.9 on 2020-08-29 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='forDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
